### ISSUE TITLE
Submit reddit link unnecessary 

### ISSUE THREAD

**Issue by johnathanmartin** [reddit/reddit-plugin-about#71]
On the postcard gallery there are submit widgets on all postcards to submit the postcard to the /r/postcards subreddit. This subreddit can only be submitted by mods/admins and there is no point in having the widget as users can not use it. 

![image](https://cloud.githubusercontent.com/assets/6856083/5703863/6b01e600-9a31-11e4-8d5e-74987ec72b2f.png)

![image](https://cloud.githubusercontent.com/assets/6856083/5703851/4026a11e-9a31-11e4-85ea-b34ca976dca9.png)

Please remove the widget. Thank You.

**Comment by spladug** [comment]
The purpose of the button-widget is use the "already submitted" logic to take you to the relevant automatically-generated post in /r/postcards. Unfortunately, it looks like this gets messed up when on HTTPS as reddit doesn't detect the http and https versions of the link as the same destination.

If you change the URL in your second picture to https://www.reddit.com/r/postcards/submit?url=http%3A%2F%2Fwww.reddit.com%2Fabout%2Fpostcards%2Fview%2F4208 (note the scheme of the URL) then you'll see it redirect to the appropriate submission.

**Comment by johnathanmartin** [comment]
Will this be resolved in the future?
